### <CENTER>ML ZOOMCAMP 2025 </CENTER>
### <CENTER>01 INTRO - Homework</CENTER>
### <CENTER>ANGOLE DANIEL</CENTER>

#### Set up the environment
You need to install Python, NumPy, Pandas, Matplotlib and Seaborn. For that, you can use the instructions from 06-environment.md.

<b>Q1. Pandas version</b>

What's the version of Pandas that you installed?

You can get the version information using the `__version__` field:

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.1'

#### Getting the data

For this homework, we'll use the Car Fuel Efficiency dataset. Download it from here.

You can do it with wget:

wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Or just open it with your browser and click "Save as...".

Now read it with Pandas.

<b>Q2. Records count</b>

How many records are in the dataset?

In [3]:
# !wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

In [4]:
df = pd.read_csv('car_fuel_efficiency.csv')

In [5]:
df.shape

(9704, 11)

In [6]:
len(df)

9704

<b>Q3. Fuel types</b>

How many fuel types are presented in the dataset?

In [7]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [8]:
df['fuel_type'].nunique()

2

In [9]:
df['fuel_type'].unique()

array(['Gasoline', 'Diesel'], dtype=object)

<b>Q4. Missing values</b>

How many columns in the dataset have missing values?

In [10]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

<b>Q5. Max fuel efficiency</b>

What's the maximum fuel efficiency of cars from Asia?

In [11]:
df.groupby('origin').fuel_efficiency_mpg.max().round(2)

origin
Asia      23.76
Europe    25.97
USA       24.97
Name: fuel_efficiency_mpg, dtype: float64

<b>Q6. Median value of horsepower</b>

1. Find the median value of horsepower column in the dataset.

2. Next, calculate the most frequent value of the same horsepower column.

3. Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.

4. Now, calculate the median value of horsepower once again.

Has it changed?

In [12]:
print(df['horsepower'].median())

149.0


In [13]:
mode = df['horsepower'].mode()[0]
print(mode)

152.0


In [14]:
df['horsepower'].fillna(mode, inplace=True)

/tmp/ipykernel_25010/3894768729.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['horsepower'].fillna(mode, inplace=True)


In [15]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower               0
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [16]:
print(df['horsepower'].median())

152.0


<b>Q7. Sum of weights</b>

1. Select all the cars from Asia
2. Select only columns vehicle_weight and model_year
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Invert XTX.
7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9. What's the sum of all the elements of the result?

Note: You just implemented linear regression. We'll talk about it in the next lesson.

In [17]:
# Select all the cars from Asia
df_asia = df[df['origin'] == 'Asia']

In [18]:
df_asia

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0       152.0     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [19]:
# Select only columns vehicle_weight and model_year
df_asia_wight_year = df_asia[['vehicle_weight', 'model_year']]

In [20]:
# Select the first 7 values
df_asia_wight_year.head(7)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [21]:
x = df_asia_wight_year.head(7)

In [22]:
x

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [23]:
# Get the underlying NumPy array. Let's call it X.
import numpy as np
x = np.array(x)

In [24]:
x

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [25]:
# Compute matrix-matrix multiplication between the transpose of X and X. 
# To get the transpose, use X.T. Let's call the result XTX.
XTX = (x.T).dot(x)

In [26]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [27]:
# Invert XTX
XTX_inv = np.linalg.inv(XTX)

In [28]:
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [32]:
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200]
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [33]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. 
# Call the result w.
p = XTX_inv.dot(x.T)

In [34]:
p

array([[-1.31202622e-04, -8.63909858e-05,  3.72634923e-04,
        -4.02726650e-04, -1.62513724e-04, -5.52342829e-05,
         4.65094049e-04],
       [ 2.62636846e-04,  1.96990690e-04, -4.73392228e-04,
         6.58944477e-04,  3.08357831e-04,  1.51636137e-04,
        -6.07979633e-04]])

In [35]:
w = p.dot(y)

In [36]:
w

array([0.01386421, 0.5049067 ])

In [37]:
# What's the sum of all the elements of the result?
sum = w.sum()

In [41]:
print(sum.round(2))

0.52
